# Site settings
title: WS Client
description: A simple websocket client
url: https://dylansallred.github.io

# Theme settings
theme: jekyll-theme-minimal
google_analytics: # Add your Google Analytics ID here if needed

# Build settings
markdown: kramdown 